version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - revive
    - bodyclose
    - contextcheck
    - dupl
    - goconst
    - gocyclo
    - misspell

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style

  revive:
    ignoreGeneratedHeader: true
    severity: warning
    rules:
      - name: indent-error-flow
      - name: exported
      - name: rangeValCopy
      - name: receiver-naming
      - name: blank-imports
      - name: unused-parameter
      - name: unnecessary-stmt
      - name: unnecessary-return

  gocyclo:
    min-complexity: 15

issues:
  exclude-use-default: false
  max-same-issues: 50
  exclude:
    - "should have comment"
    - "comment on exported"