#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE mattermost;
    CREATE DATABASE keycloak;
    GRANT ALL PRIVILEGES ON DATABASE mattermost TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE keycloak TO "$POSTGRES_USER";
EOSQL